syntax = "proto3";

package similarityhit;
option go_package = "web/protos;";

// ------------------------------------------------
// PLATFORM
// ------------------------------------------------

enum Platform {
  POLYMARKET = 0;
  KALSHI = 1;
}

// ------------------------------------------------
// SIMILARITY HIT
// ------------------------------------------------

message MarketInfo {
    string uuid = 1;
    string market_id = 2;
    string question = 3;
    string outcome = 4;
    string rules = 5;
    string market_category = 6;
    string market_subcategory = 7;
    Platform platform = 8;
    string end_date = 9;
}

message QdrantPayload {
    MarketInfo market_info = 1;
    int64 qdrant_inserted_at = 10; 
}

message MatchCandidate {
    float scored = 1;
    MarketInfo market_info = 2;
}

message SimilarityHit {
    MarketInfo anchor = 1;
    repeated MatchCandidate matches = 2;
}

// ------------------------------------------------
// DISCOVERY
// ------------------------------------------------

enum Leg {
  LEG_LEFT = 0;  
  LEG_RIGHT = 1; 
}

message Discovery {
  MarketInfo market_info = 1;
  Leg leg = 2;
  string leg_str = 3;
}

message DiscoveredArb {
  Discovery anchor = 1;
  Discovery match = 2;
  float scored = 3;
}

message DiscoveredArbList {
    repeated DiscoveredArb arbs = 1;
}

// ------------------------------------------------
// ARB
// ------------------------------------------------

message ArbEssentials {
  Discovery discovery = 1;
  string token_id = 2;
}

message Arb {
  ArbEssentials anchor = 1;
  ArbEssentials match = 2;
  float scored = 3;
}

// ------------------------------------------------
// THE ENVELOPE
// ------------------------------------------------

message ClientEbo {
    string correlation_id = 1;
    int64 found_at = 2;

    oneof action {
        SimilarityHit cross_platform_hit = 3;
        SimilarityHit intra_platform_hit = 4;

        Arb cross_platform_arb = 5;
        Arb intra_platform_arb = 6;
    }
}
message ServerEbo {
    string correlation_id = 1;
    int64 found_at = 2;

    oneof action {
        DiscoveredArbList cross_platform_arb_discovery = 3;
        DiscoveredArbList intra_platform_arb_discovery = 4;

        Arb confirmed_and_run = 5;
    }
}

service EsuOdara {
  rpc Esu(stream ClientEbo) returns (stream ServerEbo);
}

