// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: similarity_hit.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EsuOdara_Esu_FullMethodName = "/similarityhit.EsuOdara/Esu"
)

// EsuOdaraClient is the client API for EsuOdara service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EsuOdaraClient interface {
	Esu(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ebo, Ebo], error)
}

type esuOdaraClient struct {
	cc grpc.ClientConnInterface
}

func NewEsuOdaraClient(cc grpc.ClientConnInterface) EsuOdaraClient {
	return &esuOdaraClient{cc}
}

func (c *esuOdaraClient) Esu(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ebo, Ebo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EsuOdara_ServiceDesc.Streams[0], EsuOdara_Esu_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ebo, Ebo]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EsuOdara_EsuClient = grpc.BidiStreamingClient[Ebo, Ebo]

// EsuOdaraServer is the server API for EsuOdara service.
// All implementations must embed UnimplementedEsuOdaraServer
// for forward compatibility.
type EsuOdaraServer interface {
	Esu(grpc.BidiStreamingServer[Ebo, Ebo]) error
	mustEmbedUnimplementedEsuOdaraServer()
}

// UnimplementedEsuOdaraServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEsuOdaraServer struct{}

func (UnimplementedEsuOdaraServer) Esu(grpc.BidiStreamingServer[Ebo, Ebo]) error {
	return status.Error(codes.Unimplemented, "method Esu not implemented")
}
func (UnimplementedEsuOdaraServer) mustEmbedUnimplementedEsuOdaraServer() {}
func (UnimplementedEsuOdaraServer) testEmbeddedByValue()                  {}

// UnsafeEsuOdaraServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EsuOdaraServer will
// result in compilation errors.
type UnsafeEsuOdaraServer interface {
	mustEmbedUnimplementedEsuOdaraServer()
}

func RegisterEsuOdaraServer(s grpc.ServiceRegistrar, srv EsuOdaraServer) {
	// If the following call panics, it indicates UnimplementedEsuOdaraServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EsuOdara_ServiceDesc, srv)
}

func _EsuOdara_Esu_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EsuOdaraServer).Esu(&grpc.GenericServerStream[Ebo, Ebo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EsuOdara_EsuServer = grpc.BidiStreamingServer[Ebo, Ebo]

// EsuOdara_ServiceDesc is the grpc.ServiceDesc for EsuOdara service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EsuOdara_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "similarityhit.EsuOdara",
	HandlerType: (*EsuOdaraServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Esu",
			Handler:       _EsuOdara_Esu_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "similarity_hit.proto",
}
