// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: similarity_hit.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QdrantPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Question          string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Outcome           string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	ClobTokenIds      string                 `protobuf:"bytes,4,opt,name=clob_token_ids,json=clobTokenIds,proto3" json:"clob_token_ids,omitempty"`
	Rules             string                 `protobuf:"bytes,5,opt,name=rules,proto3" json:"rules,omitempty"`
	MarketId          string                 `protobuf:"bytes,6,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	MarketCategory    string                 `protobuf:"bytes,7,opt,name=market_category,json=marketCategory,proto3" json:"market_category,omitempty"`
	MarketSubcategory string                 `protobuf:"bytes,8,opt,name=market_subcategory,json=marketSubcategory,proto3" json:"market_subcategory,omitempty"`
	Platform          string                 `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`
	EndDate           string                 `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	InsertedAt        int64                  `protobuf:"varint,11,opt,name=inserted_at,json=insertedAt,proto3" json:"inserted_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QdrantPayload) Reset() {
	*x = QdrantPayload{}
	mi := &file_similarity_hit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QdrantPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QdrantPayload) ProtoMessage() {}

func (x *QdrantPayload) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QdrantPayload.ProtoReflect.Descriptor instead.
func (*QdrantPayload) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{0}
}

func (x *QdrantPayload) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *QdrantPayload) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QdrantPayload) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *QdrantPayload) GetClobTokenIds() string {
	if x != nil {
		return x.ClobTokenIds
	}
	return ""
}

func (x *QdrantPayload) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *QdrantPayload) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *QdrantPayload) GetMarketCategory() string {
	if x != nil {
		return x.MarketCategory
	}
	return ""
}

func (x *QdrantPayload) GetMarketSubcategory() string {
	if x != nil {
		return x.MarketSubcategory
	}
	return ""
}

func (x *QdrantPayload) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *QdrantPayload) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *QdrantPayload) GetInsertedAt() int64 {
	if x != nil {
		return x.InsertedAt
	}
	return 0
}

type Matches struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scored        float32                `protobuf:"fixed32,1,opt,name=scored,proto3" json:"scored,omitempty"`
	Match         *QdrantPayload         `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matches) Reset() {
	*x = Matches{}
	mi := &file_similarity_hit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matches) ProtoMessage() {}

func (x *Matches) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matches.ProtoReflect.Descriptor instead.
func (*Matches) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{1}
}

func (x *Matches) GetScored() float32 {
	if x != nil {
		return x.Scored
	}
	return 0
}

func (x *Matches) GetMatch() *QdrantPayload {
	if x != nil {
		return x.Match
	}
	return nil
}

type SimilarityHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchor        *QdrantPayload         `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Matches       []*Matches             `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityHit) Reset() {
	*x = SimilarityHit{}
	mi := &file_similarity_hit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityHit) ProtoMessage() {}

func (x *SimilarityHit) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityHit.ProtoReflect.Descriptor instead.
func (*SimilarityHit) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{2}
}

func (x *SimilarityHit) GetAnchor() *QdrantPayload {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *SimilarityHit) GetMatches() []*Matches {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Ebo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ArbFoundAt    int64                  `protobuf:"varint,2,opt,name=arb_found_at,json=arbFoundAt,proto3" json:"arb_found_at,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*Ebo_CrossPlatformArb
	//	*Ebo_IntraPlatformArb
	Action        isEbo_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ebo) Reset() {
	*x = Ebo{}
	mi := &file_similarity_hit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ebo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ebo) ProtoMessage() {}

func (x *Ebo) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ebo.ProtoReflect.Descriptor instead.
func (*Ebo) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{3}
}

func (x *Ebo) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Ebo) GetArbFoundAt() int64 {
	if x != nil {
		return x.ArbFoundAt
	}
	return 0
}

func (x *Ebo) GetAction() isEbo_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Ebo) GetCrossPlatformArb() *SimilarityHit {
	if x != nil {
		if x, ok := x.Action.(*Ebo_CrossPlatformArb); ok {
			return x.CrossPlatformArb
		}
	}
	return nil
}

func (x *Ebo) GetIntraPlatformArb() *SimilarityHit {
	if x != nil {
		if x, ok := x.Action.(*Ebo_IntraPlatformArb); ok {
			return x.IntraPlatformArb
		}
	}
	return nil
}

type isEbo_Action interface {
	isEbo_Action()
}

type Ebo_CrossPlatformArb struct {
	CrossPlatformArb *SimilarityHit `protobuf:"bytes,3,opt,name=cross_platform_arb,json=crossPlatformArb,proto3,oneof"`
}

type Ebo_IntraPlatformArb struct {
	IntraPlatformArb *SimilarityHit `protobuf:"bytes,4,opt,name=intra_platform_arb,json=intraPlatformArb,proto3,oneof"`
}

func (*Ebo_CrossPlatformArb) isEbo_Action() {}

func (*Ebo_IntraPlatformArb) isEbo_Action() {}

var File_similarity_hit_proto protoreflect.FileDescriptor

const file_similarity_hit_proto_rawDesc = "" +
	"\n" +
	"\x14similarity_hit.proto\x12\rsimilarityhit\"\xe2\x02\n" +
	"\rQdrantPayload\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12$\n" +
	"\x0eclob_token_ids\x18\x04 \x01(\tR\fclobTokenIds\x12\x14\n" +
	"\x05rules\x18\x05 \x01(\tR\x05rules\x12\x1b\n" +
	"\tmarket_id\x18\x06 \x01(\tR\bmarketId\x12'\n" +
	"\x0fmarket_category\x18\a \x01(\tR\x0emarketCategory\x12-\n" +
	"\x12market_subcategory\x18\b \x01(\tR\x11marketSubcategory\x12\x1a\n" +
	"\bplatform\x18\t \x01(\tR\bplatform\x12\x19\n" +
	"\bend_date\x18\n" +
	" \x01(\tR\aendDate\x12\x1f\n" +
	"\vinserted_at\x18\v \x01(\x03R\n" +
	"insertedAt\"U\n" +
	"\aMatches\x12\x16\n" +
	"\x06scored\x18\x01 \x01(\x02R\x06scored\x122\n" +
	"\x05match\x18\x02 \x01(\v2\x1c.similarityhit.QdrantPayloadR\x05match\"w\n" +
	"\rSimilarityHit\x124\n" +
	"\x06anchor\x18\x01 \x01(\v2\x1c.similarityhit.QdrantPayloadR\x06anchor\x120\n" +
	"\amatches\x18\x02 \x03(\v2\x16.similarityhit.MatchesR\amatches\"\xf4\x01\n" +
	"\x03Ebo\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12 \n" +
	"\farb_found_at\x18\x02 \x01(\x03R\n" +
	"arbFoundAt\x12L\n" +
	"\x12cross_platform_arb\x18\x03 \x01(\v2\x1c.similarityhit.SimilarityHitH\x00R\x10crossPlatformArb\x12L\n" +
	"\x12intra_platform_arb\x18\x04 \x01(\v2\x1c.similarityhit.SimilarityHitH\x00R\x10intraPlatformArbB\b\n" +
	"\x06action2=\n" +
	"\bEsuOdara\x121\n" +
	"\x03Esu\x12\x12.similarityhit.Ebo\x1a\x12.similarityhit.Ebo(\x010\x01B\rZ\vweb/protos;b\x06proto3"

var (
	file_similarity_hit_proto_rawDescOnce sync.Once
	file_similarity_hit_proto_rawDescData []byte
)

func file_similarity_hit_proto_rawDescGZIP() []byte {
	file_similarity_hit_proto_rawDescOnce.Do(func() {
		file_similarity_hit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_similarity_hit_proto_rawDesc), len(file_similarity_hit_proto_rawDesc)))
	})
	return file_similarity_hit_proto_rawDescData
}

var file_similarity_hit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_similarity_hit_proto_goTypes = []any{
	(*QdrantPayload)(nil), // 0: similarityhit.QdrantPayload
	(*Matches)(nil),       // 1: similarityhit.Matches
	(*SimilarityHit)(nil), // 2: similarityhit.SimilarityHit
	(*Ebo)(nil),           // 3: similarityhit.Ebo
}
var file_similarity_hit_proto_depIdxs = []int32{
	0, // 0: similarityhit.Matches.match:type_name -> similarityhit.QdrantPayload
	0, // 1: similarityhit.SimilarityHit.anchor:type_name -> similarityhit.QdrantPayload
	1, // 2: similarityhit.SimilarityHit.matches:type_name -> similarityhit.Matches
	2, // 3: similarityhit.Ebo.cross_platform_arb:type_name -> similarityhit.SimilarityHit
	2, // 4: similarityhit.Ebo.intra_platform_arb:type_name -> similarityhit.SimilarityHit
	3, // 5: similarityhit.EsuOdara.Esu:input_type -> similarityhit.Ebo
	3, // 6: similarityhit.EsuOdara.Esu:output_type -> similarityhit.Ebo
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_similarity_hit_proto_init() }
func file_similarity_hit_proto_init() {
	if File_similarity_hit_proto != nil {
		return
	}
	file_similarity_hit_proto_msgTypes[3].OneofWrappers = []any{
		(*Ebo_CrossPlatformArb)(nil),
		(*Ebo_IntraPlatformArb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_similarity_hit_proto_rawDesc), len(file_similarity_hit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_similarity_hit_proto_goTypes,
		DependencyIndexes: file_similarity_hit_proto_depIdxs,
		MessageInfos:      file_similarity_hit_proto_msgTypes,
	}.Build()
	File_similarity_hit_proto = out.File
	file_similarity_hit_proto_goTypes = nil
	file_similarity_hit_proto_depIdxs = nil
}
