// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: similarity_hit.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Esu_EsuStream_FullMethodName = "/similarityhit.Esu/EsuStream"
)

// EsuClient is the client API for Esu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EsuClient interface {
	EsuStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ebo, Ebo], error)
}

type esuClient struct {
	cc grpc.ClientConnInterface
}

func NewEsuClient(cc grpc.ClientConnInterface) EsuClient {
	return &esuClient{cc}
}

func (c *esuClient) EsuStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ebo, Ebo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Esu_ServiceDesc.Streams[0], Esu_EsuStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ebo, Ebo]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Esu_EsuStreamClient = grpc.BidiStreamingClient[Ebo, Ebo]

// EsuServer is the server API for Esu service.
// All implementations must embed UnimplementedEsuServer
// for forward compatibility.
type EsuServer interface {
	EsuStream(grpc.BidiStreamingServer[Ebo, Ebo]) error
	mustEmbedUnimplementedEsuServer()
}

// UnimplementedEsuServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEsuServer struct{}

func (UnimplementedEsuServer) EsuStream(grpc.BidiStreamingServer[Ebo, Ebo]) error {
	return status.Error(codes.Unimplemented, "method EsuStream not implemented")
}
func (UnimplementedEsuServer) mustEmbedUnimplementedEsuServer() {}
func (UnimplementedEsuServer) testEmbeddedByValue()             {}

// UnsafeEsuServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EsuServer will
// result in compilation errors.
type UnsafeEsuServer interface {
	mustEmbedUnimplementedEsuServer()
}

func RegisterEsuServer(s grpc.ServiceRegistrar, srv EsuServer) {
	// If the following call panics, it indicates UnimplementedEsuServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Esu_ServiceDesc, srv)
}

func _Esu_EsuStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EsuServer).EsuStream(&grpc.GenericServerStream[Ebo, Ebo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Esu_EsuStreamServer = grpc.BidiStreamingServer[Ebo, Ebo]

// Esu_ServiceDesc is the grpc.ServiceDesc for Esu service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Esu_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "similarityhit.Esu",
	HandlerType: (*EsuServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EsuStream",
			Handler:       _Esu_EsuStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "similarity_hit.proto",
}
