// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: similarity_hit.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_POLYMARKET Platform = 0
	Platform_KALSHI     Platform = 1
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "POLYMARKET",
		1: "KALSHI",
	}
	Platform_value = map[string]int32{
		"POLYMARKET": 0,
		"KALSHI":     1,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_similarity_hit_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_similarity_hit_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{0}
}

type Leg int32

const (
	Leg_LEG_LEFT  Leg = 0
	Leg_LEG_RIGHT Leg = 1
)

// Enum value maps for Leg.
var (
	Leg_name = map[int32]string{
		0: "LEG_LEFT",
		1: "LEG_RIGHT",
	}
	Leg_value = map[string]int32{
		"LEG_LEFT":  0,
		"LEG_RIGHT": 1,
	}
)

func (x Leg) Enum() *Leg {
	p := new(Leg)
	*p = x
	return p
}

func (x Leg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Leg) Descriptor() protoreflect.EnumDescriptor {
	return file_similarity_hit_proto_enumTypes[1].Descriptor()
}

func (Leg) Type() protoreflect.EnumType {
	return &file_similarity_hit_proto_enumTypes[1]
}

func (x Leg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Leg.Descriptor instead.
func (Leg) EnumDescriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{1}
}

type MarketInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MarketId          string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Question          string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Outcome           string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Rules             string                 `protobuf:"bytes,5,opt,name=rules,proto3" json:"rules,omitempty"`
	MarketCategory    string                 `protobuf:"bytes,6,opt,name=market_category,json=marketCategory,proto3" json:"market_category,omitempty"`
	MarketSubcategory string                 `protobuf:"bytes,7,opt,name=market_subcategory,json=marketSubcategory,proto3" json:"market_subcategory,omitempty"`
	Platform          Platform               `protobuf:"varint,8,opt,name=platform,proto3,enum=similarityhit.Platform" json:"platform,omitempty"`
	EndDate           string                 `protobuf:"bytes,9,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MarketInfo) Reset() {
	*x = MarketInfo{}
	mi := &file_similarity_hit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketInfo) ProtoMessage() {}

func (x *MarketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketInfo.ProtoReflect.Descriptor instead.
func (*MarketInfo) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{0}
}

func (x *MarketInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MarketInfo) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MarketInfo) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MarketInfo) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *MarketInfo) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *MarketInfo) GetMarketCategory() string {
	if x != nil {
		return x.MarketCategory
	}
	return ""
}

func (x *MarketInfo) GetMarketSubcategory() string {
	if x != nil {
		return x.MarketSubcategory
	}
	return ""
}

func (x *MarketInfo) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_POLYMARKET
}

func (x *MarketInfo) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type QdrantPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MarketInfo       *MarketInfo            `protobuf:"bytes,1,opt,name=market_info,json=marketInfo,proto3" json:"market_info,omitempty"`
	QdrantInsertedAt int64                  `protobuf:"varint,10,opt,name=qdrant_inserted_at,json=qdrantInsertedAt,proto3" json:"qdrant_inserted_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QdrantPayload) Reset() {
	*x = QdrantPayload{}
	mi := &file_similarity_hit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QdrantPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QdrantPayload) ProtoMessage() {}

func (x *QdrantPayload) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QdrantPayload.ProtoReflect.Descriptor instead.
func (*QdrantPayload) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{1}
}

func (x *QdrantPayload) GetMarketInfo() *MarketInfo {
	if x != nil {
		return x.MarketInfo
	}
	return nil
}

func (x *QdrantPayload) GetQdrantInsertedAt() int64 {
	if x != nil {
		return x.QdrantInsertedAt
	}
	return 0
}

type MatchCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scored        float32                `protobuf:"fixed32,1,opt,name=scored,proto3" json:"scored,omitempty"`
	MarketInfo    *MarketInfo            `protobuf:"bytes,2,opt,name=market_info,json=marketInfo,proto3" json:"market_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCandidate) Reset() {
	*x = MatchCandidate{}
	mi := &file_similarity_hit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCandidate) ProtoMessage() {}

func (x *MatchCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCandidate.ProtoReflect.Descriptor instead.
func (*MatchCandidate) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{2}
}

func (x *MatchCandidate) GetScored() float32 {
	if x != nil {
		return x.Scored
	}
	return 0
}

func (x *MatchCandidate) GetMarketInfo() *MarketInfo {
	if x != nil {
		return x.MarketInfo
	}
	return nil
}

type SimilarityHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchor        *MarketInfo            `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Matches       []*MatchCandidate      `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityHit) Reset() {
	*x = SimilarityHit{}
	mi := &file_similarity_hit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityHit) ProtoMessage() {}

func (x *SimilarityHit) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityHit.ProtoReflect.Descriptor instead.
func (*SimilarityHit) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{3}
}

func (x *SimilarityHit) GetAnchor() *MarketInfo {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *SimilarityHit) GetMatches() []*MatchCandidate {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Discovery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketInfo    *MarketInfo            `protobuf:"bytes,1,opt,name=market_info,json=marketInfo,proto3" json:"market_info,omitempty"`
	Leg           Leg                    `protobuf:"varint,2,opt,name=leg,proto3,enum=similarityhit.Leg" json:"leg,omitempty"`
	LegStr        string                 `protobuf:"bytes,3,opt,name=leg_str,json=legStr,proto3" json:"leg_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discovery) Reset() {
	*x = Discovery{}
	mi := &file_similarity_hit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery) ProtoMessage() {}

func (x *Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery.ProtoReflect.Descriptor instead.
func (*Discovery) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{4}
}

func (x *Discovery) GetMarketInfo() *MarketInfo {
	if x != nil {
		return x.MarketInfo
	}
	return nil
}

func (x *Discovery) GetLeg() Leg {
	if x != nil {
		return x.Leg
	}
	return Leg_LEG_LEFT
}

func (x *Discovery) GetLegStr() string {
	if x != nil {
		return x.LegStr
	}
	return ""
}

type DiscoveredArb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchor        *Discovery             `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Match         *Discovery             `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	Scored        float32                `protobuf:"fixed32,3,opt,name=scored,proto3" json:"scored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredArb) Reset() {
	*x = DiscoveredArb{}
	mi := &file_similarity_hit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredArb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredArb) ProtoMessage() {}

func (x *DiscoveredArb) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredArb.ProtoReflect.Descriptor instead.
func (*DiscoveredArb) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoveredArb) GetAnchor() *Discovery {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *DiscoveredArb) GetMatch() *Discovery {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *DiscoveredArb) GetScored() float32 {
	if x != nil {
		return x.Scored
	}
	return 0
}

type DiscoveredArbList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arbs          []*DiscoveredArb       `protobuf:"bytes,1,rep,name=arbs,proto3" json:"arbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredArbList) Reset() {
	*x = DiscoveredArbList{}
	mi := &file_similarity_hit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredArbList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredArbList) ProtoMessage() {}

func (x *DiscoveredArbList) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredArbList.ProtoReflect.Descriptor instead.
func (*DiscoveredArbList) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoveredArbList) GetArbs() []*DiscoveredArb {
	if x != nil {
		return x.Arbs
	}
	return nil
}

type ArbEssentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discovery     *Discovery             `protobuf:"bytes,1,opt,name=discovery,proto3" json:"discovery,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbEssentials) Reset() {
	*x = ArbEssentials{}
	mi := &file_similarity_hit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbEssentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbEssentials) ProtoMessage() {}

func (x *ArbEssentials) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbEssentials.ProtoReflect.Descriptor instead.
func (*ArbEssentials) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{7}
}

func (x *ArbEssentials) GetDiscovery() *Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *ArbEssentials) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type Arb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchor        *ArbEssentials         `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Match         *ArbEssentials         `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	Scored        float32                `protobuf:"fixed32,3,opt,name=scored,proto3" json:"scored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arb) Reset() {
	*x = Arb{}
	mi := &file_similarity_hit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arb) ProtoMessage() {}

func (x *Arb) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arb.ProtoReflect.Descriptor instead.
func (*Arb) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{8}
}

func (x *Arb) GetAnchor() *ArbEssentials {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *Arb) GetMatch() *ArbEssentials {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Arb) GetScored() float32 {
	if x != nil {
		return x.Scored
	}
	return 0
}

type ClientEbo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	FoundAt       int64                  `protobuf:"varint,2,opt,name=found_at,json=foundAt,proto3" json:"found_at,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*ClientEbo_CrossPlatformHit
	//	*ClientEbo_IntraPlatformHit
	//	*ClientEbo_CrossPlatformArb
	//	*ClientEbo_IntraPlatformArb
	Action        isClientEbo_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEbo) Reset() {
	*x = ClientEbo{}
	mi := &file_similarity_hit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEbo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEbo) ProtoMessage() {}

func (x *ClientEbo) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEbo.ProtoReflect.Descriptor instead.
func (*ClientEbo) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{9}
}

func (x *ClientEbo) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ClientEbo) GetFoundAt() int64 {
	if x != nil {
		return x.FoundAt
	}
	return 0
}

func (x *ClientEbo) GetAction() isClientEbo_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ClientEbo) GetCrossPlatformHit() *SimilarityHit {
	if x != nil {
		if x, ok := x.Action.(*ClientEbo_CrossPlatformHit); ok {
			return x.CrossPlatformHit
		}
	}
	return nil
}

func (x *ClientEbo) GetIntraPlatformHit() *SimilarityHit {
	if x != nil {
		if x, ok := x.Action.(*ClientEbo_IntraPlatformHit); ok {
			return x.IntraPlatformHit
		}
	}
	return nil
}

func (x *ClientEbo) GetCrossPlatformArb() *Arb {
	if x != nil {
		if x, ok := x.Action.(*ClientEbo_CrossPlatformArb); ok {
			return x.CrossPlatformArb
		}
	}
	return nil
}

func (x *ClientEbo) GetIntraPlatformArb() *Arb {
	if x != nil {
		if x, ok := x.Action.(*ClientEbo_IntraPlatformArb); ok {
			return x.IntraPlatformArb
		}
	}
	return nil
}

type isClientEbo_Action interface {
	isClientEbo_Action()
}

type ClientEbo_CrossPlatformHit struct {
	CrossPlatformHit *SimilarityHit `protobuf:"bytes,3,opt,name=cross_platform_hit,json=crossPlatformHit,proto3,oneof"`
}

type ClientEbo_IntraPlatformHit struct {
	IntraPlatformHit *SimilarityHit `protobuf:"bytes,4,opt,name=intra_platform_hit,json=intraPlatformHit,proto3,oneof"`
}

type ClientEbo_CrossPlatformArb struct {
	CrossPlatformArb *Arb `protobuf:"bytes,5,opt,name=cross_platform_arb,json=crossPlatformArb,proto3,oneof"`
}

type ClientEbo_IntraPlatformArb struct {
	IntraPlatformArb *Arb `protobuf:"bytes,6,opt,name=intra_platform_arb,json=intraPlatformArb,proto3,oneof"`
}

func (*ClientEbo_CrossPlatformHit) isClientEbo_Action() {}

func (*ClientEbo_IntraPlatformHit) isClientEbo_Action() {}

func (*ClientEbo_CrossPlatformArb) isClientEbo_Action() {}

func (*ClientEbo_IntraPlatformArb) isClientEbo_Action() {}

type ServerEbo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	FoundAt       int64                  `protobuf:"varint,2,opt,name=found_at,json=foundAt,proto3" json:"found_at,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*ServerEbo_CrossPlatformArbDiscovery
	//	*ServerEbo_IntraPlatformArbDiscovery
	//	*ServerEbo_ConfirmedAndRun
	Action        isServerEbo_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEbo) Reset() {
	*x = ServerEbo{}
	mi := &file_similarity_hit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEbo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEbo) ProtoMessage() {}

func (x *ServerEbo) ProtoReflect() protoreflect.Message {
	mi := &file_similarity_hit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEbo.ProtoReflect.Descriptor instead.
func (*ServerEbo) Descriptor() ([]byte, []int) {
	return file_similarity_hit_proto_rawDescGZIP(), []int{10}
}

func (x *ServerEbo) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ServerEbo) GetFoundAt() int64 {
	if x != nil {
		return x.FoundAt
	}
	return 0
}

func (x *ServerEbo) GetAction() isServerEbo_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ServerEbo) GetCrossPlatformArbDiscovery() *DiscoveredArbList {
	if x != nil {
		if x, ok := x.Action.(*ServerEbo_CrossPlatformArbDiscovery); ok {
			return x.CrossPlatformArbDiscovery
		}
	}
	return nil
}

func (x *ServerEbo) GetIntraPlatformArbDiscovery() *DiscoveredArbList {
	if x != nil {
		if x, ok := x.Action.(*ServerEbo_IntraPlatformArbDiscovery); ok {
			return x.IntraPlatformArbDiscovery
		}
	}
	return nil
}

func (x *ServerEbo) GetConfirmedAndRun() *Arb {
	if x != nil {
		if x, ok := x.Action.(*ServerEbo_ConfirmedAndRun); ok {
			return x.ConfirmedAndRun
		}
	}
	return nil
}

type isServerEbo_Action interface {
	isServerEbo_Action()
}

type ServerEbo_CrossPlatformArbDiscovery struct {
	CrossPlatformArbDiscovery *DiscoveredArbList `protobuf:"bytes,3,opt,name=cross_platform_arb_discovery,json=crossPlatformArbDiscovery,proto3,oneof"`
}

type ServerEbo_IntraPlatformArbDiscovery struct {
	IntraPlatformArbDiscovery *DiscoveredArbList `protobuf:"bytes,4,opt,name=intra_platform_arb_discovery,json=intraPlatformArbDiscovery,proto3,oneof"`
}

type ServerEbo_ConfirmedAndRun struct {
	ConfirmedAndRun *Arb `protobuf:"bytes,5,opt,name=confirmed_and_run,json=confirmedAndRun,proto3,oneof"`
}

func (*ServerEbo_CrossPlatformArbDiscovery) isServerEbo_Action() {}

func (*ServerEbo_IntraPlatformArbDiscovery) isServerEbo_Action() {}

func (*ServerEbo_ConfirmedAndRun) isServerEbo_Action() {}

var File_similarity_hit_proto protoreflect.FileDescriptor

const file_similarity_hit_proto_rawDesc = "" +
	"\n" +
	"\x14similarity_hit.proto\x12\rsimilarityhit\"\xb1\x02\n" +
	"\n" +
	"MarketInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12\x14\n" +
	"\x05rules\x18\x05 \x01(\tR\x05rules\x12'\n" +
	"\x0fmarket_category\x18\x06 \x01(\tR\x0emarketCategory\x12-\n" +
	"\x12market_subcategory\x18\a \x01(\tR\x11marketSubcategory\x123\n" +
	"\bplatform\x18\b \x01(\x0e2\x17.similarityhit.PlatformR\bplatform\x12\x19\n" +
	"\bend_date\x18\t \x01(\tR\aendDate\"y\n" +
	"\rQdrantPayload\x12:\n" +
	"\vmarket_info\x18\x01 \x01(\v2\x19.similarityhit.MarketInfoR\n" +
	"marketInfo\x12,\n" +
	"\x12qdrant_inserted_at\x18\n" +
	" \x01(\x03R\x10qdrantInsertedAt\"d\n" +
	"\x0eMatchCandidate\x12\x16\n" +
	"\x06scored\x18\x01 \x01(\x02R\x06scored\x12:\n" +
	"\vmarket_info\x18\x02 \x01(\v2\x19.similarityhit.MarketInfoR\n" +
	"marketInfo\"{\n" +
	"\rSimilarityHit\x121\n" +
	"\x06anchor\x18\x01 \x01(\v2\x19.similarityhit.MarketInfoR\x06anchor\x127\n" +
	"\amatches\x18\x02 \x03(\v2\x1d.similarityhit.MatchCandidateR\amatches\"\x86\x01\n" +
	"\tDiscovery\x12:\n" +
	"\vmarket_info\x18\x01 \x01(\v2\x19.similarityhit.MarketInfoR\n" +
	"marketInfo\x12$\n" +
	"\x03leg\x18\x02 \x01(\x0e2\x12.similarityhit.LegR\x03leg\x12\x17\n" +
	"\aleg_str\x18\x03 \x01(\tR\x06legStr\"\x89\x01\n" +
	"\rDiscoveredArb\x120\n" +
	"\x06anchor\x18\x01 \x01(\v2\x18.similarityhit.DiscoveryR\x06anchor\x12.\n" +
	"\x05match\x18\x02 \x01(\v2\x18.similarityhit.DiscoveryR\x05match\x12\x16\n" +
	"\x06scored\x18\x03 \x01(\x02R\x06scored\"E\n" +
	"\x11DiscoveredArbList\x120\n" +
	"\x04arbs\x18\x01 \x03(\v2\x1c.similarityhit.DiscoveredArbR\x04arbs\"b\n" +
	"\rArbEssentials\x126\n" +
	"\tdiscovery\x18\x01 \x01(\v2\x18.similarityhit.DiscoveryR\tdiscovery\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"\x87\x01\n" +
	"\x03Arb\x124\n" +
	"\x06anchor\x18\x01 \x01(\v2\x1c.similarityhit.ArbEssentialsR\x06anchor\x122\n" +
	"\x05match\x18\x02 \x01(\v2\x1c.similarityhit.ArbEssentialsR\x05match\x12\x16\n" +
	"\x06scored\x18\x03 \x01(\x02R\x06scored\"\xfb\x02\n" +
	"\tClientEbo\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\bfound_at\x18\x02 \x01(\x03R\afoundAt\x12L\n" +
	"\x12cross_platform_hit\x18\x03 \x01(\v2\x1c.similarityhit.SimilarityHitH\x00R\x10crossPlatformHit\x12L\n" +
	"\x12intra_platform_hit\x18\x04 \x01(\v2\x1c.similarityhit.SimilarityHitH\x00R\x10intraPlatformHit\x12B\n" +
	"\x12cross_platform_arb\x18\x05 \x01(\v2\x12.similarityhit.ArbH\x00R\x10crossPlatformArb\x12B\n" +
	"\x12intra_platform_arb\x18\x06 \x01(\v2\x12.similarityhit.ArbH\x00R\x10intraPlatformArbB\b\n" +
	"\x06action\"\xe3\x02\n" +
	"\tServerEbo\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\bfound_at\x18\x02 \x01(\x03R\afoundAt\x12c\n" +
	"\x1ccross_platform_arb_discovery\x18\x03 \x01(\v2 .similarityhit.DiscoveredArbListH\x00R\x19crossPlatformArbDiscovery\x12c\n" +
	"\x1cintra_platform_arb_discovery\x18\x04 \x01(\v2 .similarityhit.DiscoveredArbListH\x00R\x19intraPlatformArbDiscovery\x12@\n" +
	"\x11confirmed_and_run\x18\x05 \x01(\v2\x12.similarityhit.ArbH\x00R\x0fconfirmedAndRunB\b\n" +
	"\x06action*&\n" +
	"\bPlatform\x12\x0e\n" +
	"\n" +
	"POLYMARKET\x10\x00\x12\n" +
	"\n" +
	"\x06KALSHI\x10\x01*\"\n" +
	"\x03Leg\x12\f\n" +
	"\bLEG_LEFT\x10\x00\x12\r\n" +
	"\tLEG_RIGHT\x10\x012I\n" +
	"\bEsuOdara\x12=\n" +
	"\x03Esu\x12\x18.similarityhit.ClientEbo\x1a\x18.similarityhit.ServerEbo(\x010\x01B\rZ\vweb/protos;b\x06proto3"

var (
	file_similarity_hit_proto_rawDescOnce sync.Once
	file_similarity_hit_proto_rawDescData []byte
)

func file_similarity_hit_proto_rawDescGZIP() []byte {
	file_similarity_hit_proto_rawDescOnce.Do(func() {
		file_similarity_hit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_similarity_hit_proto_rawDesc), len(file_similarity_hit_proto_rawDesc)))
	})
	return file_similarity_hit_proto_rawDescData
}

var file_similarity_hit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_similarity_hit_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_similarity_hit_proto_goTypes = []any{
	(Platform)(0),             // 0: similarityhit.Platform
	(Leg)(0),                  // 1: similarityhit.Leg
	(*MarketInfo)(nil),        // 2: similarityhit.MarketInfo
	(*QdrantPayload)(nil),     // 3: similarityhit.QdrantPayload
	(*MatchCandidate)(nil),    // 4: similarityhit.MatchCandidate
	(*SimilarityHit)(nil),     // 5: similarityhit.SimilarityHit
	(*Discovery)(nil),         // 6: similarityhit.Discovery
	(*DiscoveredArb)(nil),     // 7: similarityhit.DiscoveredArb
	(*DiscoveredArbList)(nil), // 8: similarityhit.DiscoveredArbList
	(*ArbEssentials)(nil),     // 9: similarityhit.ArbEssentials
	(*Arb)(nil),               // 10: similarityhit.Arb
	(*ClientEbo)(nil),         // 11: similarityhit.ClientEbo
	(*ServerEbo)(nil),         // 12: similarityhit.ServerEbo
}
var file_similarity_hit_proto_depIdxs = []int32{
	0,  // 0: similarityhit.MarketInfo.platform:type_name -> similarityhit.Platform
	2,  // 1: similarityhit.QdrantPayload.market_info:type_name -> similarityhit.MarketInfo
	2,  // 2: similarityhit.MatchCandidate.market_info:type_name -> similarityhit.MarketInfo
	2,  // 3: similarityhit.SimilarityHit.anchor:type_name -> similarityhit.MarketInfo
	4,  // 4: similarityhit.SimilarityHit.matches:type_name -> similarityhit.MatchCandidate
	2,  // 5: similarityhit.Discovery.market_info:type_name -> similarityhit.MarketInfo
	1,  // 6: similarityhit.Discovery.leg:type_name -> similarityhit.Leg
	6,  // 7: similarityhit.DiscoveredArb.anchor:type_name -> similarityhit.Discovery
	6,  // 8: similarityhit.DiscoveredArb.match:type_name -> similarityhit.Discovery
	7,  // 9: similarityhit.DiscoveredArbList.arbs:type_name -> similarityhit.DiscoveredArb
	6,  // 10: similarityhit.ArbEssentials.discovery:type_name -> similarityhit.Discovery
	9,  // 11: similarityhit.Arb.anchor:type_name -> similarityhit.ArbEssentials
	9,  // 12: similarityhit.Arb.match:type_name -> similarityhit.ArbEssentials
	5,  // 13: similarityhit.ClientEbo.cross_platform_hit:type_name -> similarityhit.SimilarityHit
	5,  // 14: similarityhit.ClientEbo.intra_platform_hit:type_name -> similarityhit.SimilarityHit
	10, // 15: similarityhit.ClientEbo.cross_platform_arb:type_name -> similarityhit.Arb
	10, // 16: similarityhit.ClientEbo.intra_platform_arb:type_name -> similarityhit.Arb
	8,  // 17: similarityhit.ServerEbo.cross_platform_arb_discovery:type_name -> similarityhit.DiscoveredArbList
	8,  // 18: similarityhit.ServerEbo.intra_platform_arb_discovery:type_name -> similarityhit.DiscoveredArbList
	10, // 19: similarityhit.ServerEbo.confirmed_and_run:type_name -> similarityhit.Arb
	11, // 20: similarityhit.EsuOdara.Esu:input_type -> similarityhit.ClientEbo
	12, // 21: similarityhit.EsuOdara.Esu:output_type -> similarityhit.ServerEbo
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_similarity_hit_proto_init() }
func file_similarity_hit_proto_init() {
	if File_similarity_hit_proto != nil {
		return
	}
	file_similarity_hit_proto_msgTypes[9].OneofWrappers = []any{
		(*ClientEbo_CrossPlatformHit)(nil),
		(*ClientEbo_IntraPlatformHit)(nil),
		(*ClientEbo_CrossPlatformArb)(nil),
		(*ClientEbo_IntraPlatformArb)(nil),
	}
	file_similarity_hit_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerEbo_CrossPlatformArbDiscovery)(nil),
		(*ServerEbo_IntraPlatformArbDiscovery)(nil),
		(*ServerEbo_ConfirmedAndRun)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_similarity_hit_proto_rawDesc), len(file_similarity_hit_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_similarity_hit_proto_goTypes,
		DependencyIndexes: file_similarity_hit_proto_depIdxs,
		EnumInfos:         file_similarity_hit_proto_enumTypes,
		MessageInfos:      file_similarity_hit_proto_msgTypes,
	}.Build()
	File_similarity_hit_proto = out.File
	file_similarity_hit_proto_goTypes = nil
	file_similarity_hit_proto_depIdxs = nil
}
