CREATE TABLE IF NOT EXISTS SIMILARITY_HITS (
	ID BIGSERIAL PRIMARY KEY,
	CORRELATION_ID TEXT NOT NULL UNIQUE,
	FOUND_AT TIMESTAMPTZ NOT NULL,
	SIMILARITY_HIT JSONB NOT NULL,
	ARB_TYPE TEXT NOT NULL CHECK (ARB_TYPE IN ('cross', 'intra')),
	IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
	DELETED_AT TIMESTAMPTZ,
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ARBS (
	ID BIGSERIAL PRIMARY KEY,
	CORRELATION_ID TEXT NOT NULL UNIQUE,
	FOUND_AT TIMESTAMPTZ NOT NULL,
	ARBS JSONB NOT NULL,
	CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE,
	RUNNING BOOLEAN NOT NULL DEFAULT FALSE,
	ARB_TYPE TEXT NOT NULL CHECK (ARB_TYPE IN ('cross', 'intra')),
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ORDERS (
	ID BIGSERIAL PRIMARY KEY,
	CORRELATION_ID TEXT NOT NULL UNIQUE,
	FOUND_AT TIMESTAMPTZ NOT NULL,
	ARBS JSONB,
	ANCHOR_COST NUMERIC(10, 4) NOT NULL DEFAULT 0,
	MATCH_COST NUMERIC(10, 4) NOT NULL DEFAULT 0,
	ANCHOR_FILL NUMERIC(18, 6) NOT NULL DEFAULT 0,
	MATCH_FILL NUMERIC(18, 6) NOT NULL DEFAULT 0,
	EXCESS_FILL NUMERIC(18, 6) NOT NULL DEFAULT 0,
	ANCHOR_ORDER_ID TEXT NOT NULL,
	MATCH_ORDER_ID TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS EXCESS_FILL (
	ID BIGSERIAL PRIMARY KEY,
	CORRELATION_ID TEXT NOT NULL UNIQUE,
	FOUND_AT TIMESTAMPTZ NOT NULL,
	PLATFORM VARCHAR(20) NOT NULL,
	ORDER_ID TEXT NOT NULL,
	FILL_SIZE NUMERIC(18, 6) NOT NULL DEFAULT 0,
	FILL_COST NUMERIC(18, 6) NOT NULL DEFAULT 0
);