// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package postgres

import (
	"context"
)

// iteratorForBulkInsertNeedsResolve implements pgx.CopyFromSource.
type iteratorForBulkInsertNeedsResolve struct {
	rows                 []BulkInsertNeedsResolveParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertNeedsResolve) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertNeedsResolve) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CorrelationID,
		r.rows[0].Timestamp,
		r.rows[0].SimilarityHit,
		r.rows[0].ArbType,
	}, nil
}

func (r iteratorForBulkInsertNeedsResolve) Err() error {
	return nil
}

func (q *Queries) BulkInsertNeedsResolve(ctx context.Context, arg []BulkInsertNeedsResolveParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"needs_resolve"}, []string{"correlation_id", "timestamp", "similarity_hit", "arb_type"}, &iteratorForBulkInsertNeedsResolve{rows: arg})
}
