// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package postgres

import (
	"context"
)

// iteratorForBulkInsertSimilarityHits implements pgx.CopyFromSource.
type iteratorForBulkInsertSimilarityHits struct {
	rows                 []BulkInsertSimilarityHitsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertSimilarityHits) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertSimilarityHits) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CorrelationID,
		r.rows[0].FoundAt,
		r.rows[0].SimilarityHit,
		r.rows[0].ArbType,
	}, nil
}

func (r iteratorForBulkInsertSimilarityHits) Err() error {
	return nil
}

func (q *Queries) BulkInsertSimilarityHits(ctx context.Context, arg []BulkInsertSimilarityHitsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"similarity_hits"}, []string{"correlation_id", "found_at", "similarity_hit", "arb_type"}, &iteratorForBulkInsertSimilarityHits{rows: arg})
}
