// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NeedsResolve struct {
	ID            int64              `json:"id"`
	CorrelationID string             `json:"correlation_id"`
	Timestamp     pgtype.Timestamptz `json:"timestamp"`
	SimilarityHit []byte             `json:"similarity_hit"`
	ArbType       string             `json:"arb_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
