// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type BulkInsertSimilarityHitsParams struct {
	CorrelationID string             `json:"correlation_id"`
	FoundAt       pgtype.Timestamptz `json:"found_at"`
	SimilarityHit []byte             `json:"similarity_hit"`
	ArbType       string             `json:"arb_type"`
}

const deleteArb = `-- name: DeleteArb :exec
DELETE FROM arbs
WHERE correlation_id = $1
`

func (q *Queries) DeleteArb(ctx context.Context, correlationID string) error {
	_, err := q.db.Exec(ctx, deleteArb, correlationID)
	return err
}

const deleteArbsBulk = `-- name: DeleteArbsBulk :exec
DELETE FROM arbs
WHERE correlation_id = ANY($1::text[])
`

func (q *Queries) DeleteArbsBulk(ctx context.Context, correlationIds []string) error {
	_, err := q.db.Exec(ctx, deleteArbsBulk, correlationIds)
	return err
}

const deleteSimilarityHit = `-- name: DeleteSimilarityHit :exec
UPDATE similarity_hits
SET is_deleted = TRUE,
    deleted_at = NOW()
WHERE correlation_id = $1
`

func (q *Queries) DeleteSimilarityHit(ctx context.Context, correlationID string) error {
	_, err := q.db.Exec(ctx, deleteSimilarityHit, correlationID)
	return err
}

const deleteSimilarityHitsBulk = `-- name: DeleteSimilarityHitsBulk :exec
UPDATE similarity_hits
SET is_deleted = TRUE,
    deleted_at = NOW()
WHERE correlation_id = ANY($1::text[])
`

func (q *Queries) DeleteSimilarityHitsBulk(ctx context.Context, correlationIds []string) error {
	_, err := q.db.Exec(ctx, deleteSimilarityHitsBulk, correlationIds)
	return err
}

const getAllExcessFills = `-- name: GetAllExcessFills :many
SELECT id, correlation_id, found_at, platform, order_id, fill_size, fill_cost
FROM excess_fill
ORDER BY found_at DESC
`

func (q *Queries) GetAllExcessFills(ctx context.Context) ([]ExcessFill, error) {
	rows, err := q.db.Query(ctx, getAllExcessFills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExcessFill
	for rows.Next() {
		var i ExcessFill
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.FoundAt,
			&i.Platform,
			&i.OrderID,
			&i.FillSize,
			&i.FillCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT id, correlation_id, found_at, arbs, anchor_cost, match_cost, anchor_fill, match_fill, excess_fill, anchor_order_id, match_order_id, created_at
FROM orders
ORDER BY found_at DESC
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.FoundAt,
			&i.Arbs,
			&i.AnchorCost,
			&i.MatchCost,
			&i.AnchorFill,
			&i.MatchFill,
			&i.ExcessFill,
			&i.AnchorOrderID,
			&i.MatchOrderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArbByCorrelationID = `-- name: GetArbByCorrelationID :one
SELECT id, correlation_id, found_at, arbs, confirmed, running, arb_type, created_at
FROM arbs
WHERE correlation_id = $1
`

func (q *Queries) GetArbByCorrelationID(ctx context.Context, correlationID string) (Arb, error) {
	row := q.db.QueryRow(ctx, getArbByCorrelationID, correlationID)
	var i Arb
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.FoundAt,
		&i.Arbs,
		&i.Confirmed,
		&i.Running,
		&i.ArbType,
		&i.CreatedAt,
	)
	return i, err
}

const getExcessFillByCorrelationID = `-- name: GetExcessFillByCorrelationID :one
SELECT id, correlation_id, found_at, platform, order_id, fill_size, fill_cost
FROM excess_fill
WHERE correlation_id = $1
`

func (q *Queries) GetExcessFillByCorrelationID(ctx context.Context, correlationID string) (ExcessFill, error) {
	row := q.db.QueryRow(ctx, getExcessFillByCorrelationID, correlationID)
	var i ExcessFill
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.FoundAt,
		&i.Platform,
		&i.OrderID,
		&i.FillSize,
		&i.FillCost,
	)
	return i, err
}

const getOrderByCorrelationID = `-- name: GetOrderByCorrelationID :one
SELECT id, correlation_id, found_at, arbs, anchor_cost, match_cost, anchor_fill, match_fill, excess_fill, anchor_order_id, match_order_id, created_at
FROM orders
WHERE correlation_id = $1
`

func (q *Queries) GetOrderByCorrelationID(ctx context.Context, correlationID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByCorrelationID, correlationID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.FoundAt,
		&i.Arbs,
		&i.AnchorCost,
		&i.MatchCost,
		&i.AnchorFill,
		&i.MatchFill,
		&i.ExcessFill,
		&i.AnchorOrderID,
		&i.MatchOrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderWithExcess = `-- name: GetOrderWithExcess :many
SELECT 
    o.correlation_id,
    o.found_at,
    o.arbs,
    o.anchor_cost,
    o.match_cost,
    o.anchor_fill,
    o.match_fill,
    o.excess_fill,
    o.anchor_order_id,
    o.match_order_id,
    e.platform AS hedge_platform,
    e.order_id AS hedge_order_id,
    e.fill_size AS hedge_fill_size,
    e.fill_cost AS hedge_fill_cost
FROM orders o
LEFT JOIN excess_fill e ON o.correlation_id = e.correlation_id
ORDER BY o.found_at DESC
LIMIT $1
`

type GetOrderWithExcessRow struct {
	CorrelationID string             `json:"correlation_id"`
	FoundAt       pgtype.Timestamptz `json:"found_at"`
	Arbs          []byte             `json:"arbs"`
	AnchorCost    decimal.Decimal    `json:"anchor_cost"`
	MatchCost     decimal.Decimal    `json:"match_cost"`
	AnchorFill    decimal.Decimal    `json:"anchor_fill"`
	MatchFill     decimal.Decimal    `json:"match_fill"`
	ExcessFill    decimal.Decimal    `json:"excess_fill"`
	AnchorOrderID string             `json:"anchor_order_id"`
	MatchOrderID  string             `json:"match_order_id"`
	HedgePlatform pgtype.Text        `json:"hedge_platform"`
	HedgeOrderID  pgtype.Text        `json:"hedge_order_id"`
	HedgeFillSize pgtype.Numeric     `json:"hedge_fill_size"`
	HedgeFillCost pgtype.Numeric     `json:"hedge_fill_cost"`
}

func (q *Queries) GetOrderWithExcess(ctx context.Context, limit int32) ([]GetOrderWithExcessRow, error) {
	rows, err := q.db.Query(ctx, getOrderWithExcess, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderWithExcessRow
	for rows.Next() {
		var i GetOrderWithExcessRow
		if err := rows.Scan(
			&i.CorrelationID,
			&i.FoundAt,
			&i.Arbs,
			&i.AnchorCost,
			&i.MatchCost,
			&i.AnchorFill,
			&i.MatchFill,
			&i.ExcessFill,
			&i.AnchorOrderID,
			&i.MatchOrderID,
			&i.HedgePlatform,
			&i.HedgeOrderID,
			&i.HedgeFillSize,
			&i.HedgeFillCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentArbs = `-- name: GetRecentArbs :many
SELECT id, correlation_id, found_at, arbs, confirmed, running, arb_type, created_at
FROM arbs
WHERE arb_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentArbsParams struct {
	ArbType string `json:"arb_type"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetRecentArbs(ctx context.Context, arg GetRecentArbsParams) ([]Arb, error) {
	rows, err := q.db.Query(ctx, getRecentArbs, arg.ArbType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Arb
	for rows.Next() {
		var i Arb
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.FoundAt,
			&i.Arbs,
			&i.Confirmed,
			&i.Running,
			&i.ArbType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentHits = `-- name: GetRecentHits :many
SELECT id, correlation_id, found_at, similarity_hit, arb_type, is_deleted, deleted_at, created_at
FROM similarity_hits
WHERE arb_type = $1
  AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentHitsParams struct {
	ArbType string `json:"arb_type"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetRecentHits(ctx context.Context, arg GetRecentHitsParams) ([]SimilarityHit, error) {
	rows, err := q.db.Query(ctx, getRecentHits, arg.ArbType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimilarityHit
	for rows.Next() {
		var i SimilarityHit
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.FoundAt,
			&i.SimilarityHit,
			&i.ArbType,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunninngArbs = `-- name: GetRunninngArbs :many
SELECT id, correlation_id, found_at, arbs, confirmed, running, arb_type, created_at
FROM arbs
WHERE arb_type = $1 AND running = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetRunninngArbs(ctx context.Context, arbType string) ([]Arb, error) {
	rows, err := q.db.Query(ctx, getRunninngArbs, arbType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Arb
	for rows.Next() {
		var i Arb
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.FoundAt,
			&i.Arbs,
			&i.Confirmed,
			&i.Running,
			&i.ArbType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimilarityHitByCorrelationID = `-- name: GetSimilarityHitByCorrelationID :one
SELECT id, correlation_id, found_at, similarity_hit, arb_type, is_deleted, deleted_at, created_at
FROM similarity_hits
WHERE correlation_id = $1 
    AND is_deleted = FALSE
`

func (q *Queries) GetSimilarityHitByCorrelationID(ctx context.Context, correlationID string) (SimilarityHit, error) {
	row := q.db.QueryRow(ctx, getSimilarityHitByCorrelationID, correlationID)
	var i SimilarityHit
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.FoundAt,
		&i.SimilarityHit,
		&i.ArbType,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteOldSimilarityHits = `-- name: HardDeleteOldSimilarityHits :exec
DELETE FROM similarity_hits
WHERE is_deleted = TRUE AND deleted_at < $1
`

func (q *Queries) HardDeleteOldSimilarityHits(ctx context.Context, deletedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, hardDeleteOldSimilarityHits, deletedAt)
	return err
}

const insertExcessFill = `-- name: InsertExcessFill :exec
INSERT INTO excess_fill (
    correlation_id,
    found_at,
    platform,
    order_id,
    fill_size,
    fill_cost
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertExcessFillParams struct {
	CorrelationID string             `json:"correlation_id"`
	FoundAt       pgtype.Timestamptz `json:"found_at"`
	Platform      string             `json:"platform"`
	OrderID       string             `json:"order_id"`
	FillSize      decimal.Decimal    `json:"fill_size"`
	FillCost      decimal.Decimal    `json:"fill_cost"`
}

func (q *Queries) InsertExcessFill(ctx context.Context, arg InsertExcessFillParams) error {
	_, err := q.db.Exec(ctx, insertExcessFill,
		arg.CorrelationID,
		arg.FoundAt,
		arg.Platform,
		arg.OrderID,
		arg.FillSize,
		arg.FillCost,
	)
	return err
}

const insertNewArb = `-- name: InsertNewArb :exec
INSERT INTO arbs (
    correlation_id,
    found_at,
    arbs,
    arb_type
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (correlation_id) DO NOTHING
`

type InsertNewArbParams struct {
	CorrelationID string             `json:"correlation_id"`
	FoundAt       pgtype.Timestamptz `json:"found_at"`
	Arbs          []byte             `json:"arbs"`
	ArbType       string             `json:"arb_type"`
}

func (q *Queries) InsertNewArb(ctx context.Context, arg InsertNewArbParams) error {
	_, err := q.db.Exec(ctx, insertNewArb,
		arg.CorrelationID,
		arg.FoundAt,
		arg.Arbs,
		arg.ArbType,
	)
	return err
}

const insertNewSimilarityHit = `-- name: InsertNewSimilarityHit :exec
INSERT INTO similarity_hits (
    correlation_id,
    found_at,
    similarity_hit,
    arb_type
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (correlation_id) DO NOTHING
`

type InsertNewSimilarityHitParams struct {
	CorrelationID string             `json:"correlation_id"`
	FoundAt       pgtype.Timestamptz `json:"found_at"`
	SimilarityHit []byte             `json:"similarity_hit"`
	ArbType       string             `json:"arb_type"`
}

func (q *Queries) InsertNewSimilarityHit(ctx context.Context, arg InsertNewSimilarityHitParams) error {
	_, err := q.db.Exec(ctx, insertNewSimilarityHit,
		arg.CorrelationID,
		arg.FoundAt,
		arg.SimilarityHit,
		arg.ArbType,
	)
	return err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (
    correlation_id, 
    found_at, 
    arbs, 
    anchor_cost, 
    match_cost, 
    anchor_fill, 
    match_fill, 
    excess_fill, 
    anchor_order_id, 
    match_order_id
) VALUES (
    $1,
    $2,
    (SELECT arbs.arbs FROM arbs WHERE arbs.correlation_id = $3),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type InsertOrderParams struct {
	OrderCorrelationID string             `json:"order_correlation_id"`
	FoundAt            pgtype.Timestamptz `json:"found_at"`
	ArbCorrelationID   string             `json:"arb_correlation_id"`
	AnchorCost         decimal.Decimal    `json:"anchor_cost"`
	MatchCost          decimal.Decimal    `json:"match_cost"`
	AnchorFill         decimal.Decimal    `json:"anchor_fill"`
	MatchFill          decimal.Decimal    `json:"match_fill"`
	ExcessFill         decimal.Decimal    `json:"excess_fill"`
	AnchorOrderID      string             `json:"anchor_order_id"`
	MatchOrderID       string             `json:"match_order_id"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.OrderCorrelationID,
		arg.FoundAt,
		arg.ArbCorrelationID,
		arg.AnchorCost,
		arg.MatchCost,
		arg.AnchorFill,
		arg.MatchFill,
		arg.ExcessFill,
		arg.AnchorOrderID,
		arg.MatchOrderID,
	)
	return err
}

const updateArbConfirm = `-- name: UpdateArbConfirm :exec
UPDATE arbs
SET confirmed = $2
WHERE correlation_id = $1
`

type UpdateArbConfirmParams struct {
	CorrelationID string `json:"correlation_id"`
	Confirmed     bool   `json:"confirmed"`
}

func (q *Queries) UpdateArbConfirm(ctx context.Context, arg UpdateArbConfirmParams) error {
	_, err := q.db.Exec(ctx, updateArbConfirm, arg.CorrelationID, arg.Confirmed)
	return err
}

const updateArbRunning = `-- name: UpdateArbRunning :exec
UPDATE arbs
SET running = $2
WHERE correlation_id = $1
`

type UpdateArbRunningParams struct {
	CorrelationID string `json:"correlation_id"`
	Running       bool   `json:"running"`
}

func (q *Queries) UpdateArbRunning(ctx context.Context, arg UpdateArbRunningParams) error {
	_, err := q.db.Exec(ctx, updateArbRunning, arg.CorrelationID, arg.Running)
	return err
}

const updateArbStatus = `-- name: UpdateArbStatus :one
UPDATE arbs
SET confirmed = $2,
    running = $3
WHERE correlation_id = $1
RETURNING id, correlation_id, found_at, arbs, confirmed, running, arb_type, created_at
`

type UpdateArbStatusParams struct {
	CorrelationID string `json:"correlation_id"`
	Confirmed     bool   `json:"confirmed"`
	Running       bool   `json:"running"`
}

func (q *Queries) UpdateArbStatus(ctx context.Context, arg UpdateArbStatusParams) (Arb, error) {
	row := q.db.QueryRow(ctx, updateArbStatus, arg.CorrelationID, arg.Confirmed, arg.Running)
	var i Arb
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.FoundAt,
		&i.Arbs,
		&i.Confirmed,
		&i.Running,
		&i.ArbType,
		&i.CreatedAt,
	)
	return i, err
}
